DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'oasis_app') THEN
    CREATE ROLE oasis_app LOGIN PASSWORD 'oasis_app' NOBYPASSRLS;
  END IF;
END
$$;

GRANT CONNECT ON DATABASE oasis_dev TO oasis_app;
GRANT USAGE ON SCHEMA public TO oasis_app;

ALTER DEFAULT PRIVILEGES FOR ROLE oasis IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO oasis_app;

ALTER DEFAULT PRIVILEGES FOR ROLE oasis IN SCHEMA public
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO oasis_app;
