ALTER TABLE "PaceRecord"
  ALTER COLUMN "selfTestScore" TYPE DOUBLE PRECISION USING "selfTestScore"::DOUBLE PRECISION,
  ALTER COLUMN "paceTestScore" TYPE DOUBLE PRECISION USING "paceTestScore"::DOUBLE PRECISION;
